maxfilm/urls.py
from django.conf.urls import url
from . import views

app_name = "maxfilm"
urlpatterns = [
    url(r'^signup/$', views.signup, name="signup"),
    url(r'^login/$', views.login, name="login"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^dashboard/$', views.dashboard, name="dashboard"),
    url(r'^bookmark/$', views.bookmark, name="bookmark"),
    url(r'^pending/$', views.pending, name="pending"),
    url(r'^viewed/$', views.viewed, name="viewed"),
    url(r'^add/$', views.add, name="add"),
    url(r'^$', views.index, name="index"),
    url(r'^movie/(?P<id>[0-9]+)/$', views.viewMovie, name="viewMovie"),
    url(r'^tv/(?P<id>[0-9]+)/$', views.viewTv, name="viewTv"),
    url(r'^person/(?P<id>[0-9]+)/$', views.viewPerson, name="viewPerson"),
    url(r'^search/$', views.Search, name="Search"),
    url(r'^movies/$', views.Movies, name="Movies"),
    url(r'^tv/$', views.Tv, name="Tv"),
    url(r'^people/$', views.People, name="People"),
]

mysite/urls.py
# -*- coding: utf-8 -*-
"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('maxfilm.urls', namespace='maxfilm')),
]

admin.site.site_header = u'Administración de MaxFilm'

maxfilm/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone


class AccionPelicula(models.Model):
    """Class AccionPelicula"""
    id_MovieAPI = models.CharField(max_length=20)
    titulo = models.CharField(max_length=60)
    img_portada = models.CharField(max_length=300, null=True)
    pendiente = models.BooleanField()
    vista = models.BooleanField()
    favorita = models.BooleanField()
    id_usuario = models.ForeignKey('auth.User', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Acciones Películas"

    def __str__(self):
        return "ID API: " + self.id_MovieAPI

    def __unicode__(self):
        return "ID API: " + self.id_MovieAPI


class AccionSerie(models.Model):
    """Class AccionSerie"""
    id_SerieAPI = models.CharField(max_length=20)
    titulo = models.CharField(max_length=60)
    img_portada = models.CharField(max_length=300, null=True)
    pendiente = models.BooleanField()
    vista = models.BooleanField()
    favorita = models.BooleanField()
    id_usuario = models.ForeignKey('auth.User', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Acciones Series"

    def __str__(self):
        return "ID API: " + self.id_SerieAPI

    def __unicode__(self):
        return "ID API: " + self.id_SerieAPI


class AccionPersona(models.Model):
    """Class AccionPersona"""
    id_PersonAPI = models.CharField(max_length=20)
    nombre = models.CharField(max_length=60)
    img_perfil = models.CharField(max_length=300, null=True)
    favorita = models.BooleanField()
    id_usuario = models.ForeignKey('auth.User', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Acciones Personas"

    def __str__(self):
        return "ID API: " + self.id_PersonAPI

    def __unicode__(self):
        return "ID API: " + self.id_PersonAPI


class Coleccion(models.Model):
    """Class Colecciones"""
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField(max_length=150)
    fecha_creacion = models.DateTimeField(default=timezone.now)
    coleccion_media = (
        ('Películas', 'Películas'),
        ('Series', 'Series')
    )
    media = models.CharField(max_length=10, choices=coleccion_media, default=0)
    id_usuario = models.ForeignKey('auth.User', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Colecciones"

    def __str__(self):
        return self.nombre

    def __unicode__(self):
        return self.nombre


class ContenidoMultimedia(models.Model):
    "Class ContenidoMultimedia"
    id_contentAPI = models.CharField(max_length=20)
    titulo = models.CharField(max_length=60)
    img_portada = models.CharField(max_length=300, null=True)
    id_coleccion = models.ForeignKey(Coleccion, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Contenidos Multimedia"

    def __str__(self):
        return self.titulo

    def __unicode__(self):
        return self.titulo

maxfilm/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
from models import Coleccion


class CollectionForm(ModelForm):
    class Meta:
        model = Coleccion
        fields = ['nombre', 'descripcion', 'media']

    def __init__(self, *args, **kwargs):
        super(CollectionForm, self).__init__(*args, **kwargs)
        self.fields['nombre'].required = True
        self.fields['descripcion'].required = True
        self.fields['media'].required = True


class SignUpForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password', 'email', 'first_name', 'last_name']
        widgets = {
            'password': forms.PasswordInput(),
        }

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True

maxfilm/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, render_to_response, redirect
from forms import SignUpForm, CollectionForm
from django.http import HttpResponse, HttpResponseNotFound, Http404
import json
import urllib
from urllib2 import Request, urlopen, HTTPError
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http.response import HttpResponseRedirect
from django.template.context import RequestContext
from django.contrib import auth
from django.contrib.auth.hashers import make_password
from models import AccionPelicula, AccionSerie, AccionPersona, Coleccion, ContenidoMultimedia

headers = {
    'Accept': 'application/json',
    }


def login(request):
    """Login"""

    username = request.POST['username']
    password = request.POST['password']
    user = auth.authenticate(username=username, password=password)

    if user is not None and user.is_active:
        auth.login(request, user)
        request.session['login'] = user.first_name
        return HttpResponseRedirect("/dashboard/")
    else:
        request.session['login'] = 'error'
        return HttpResponseRedirect('/')


def logout(request):
    """Logout"""

    del request.session['login']
    auth.logout(request)

    return HttpResponseRedirect('/')


def signup(request):
    """Signup"""

    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            email = form.cleaned_data["email"]
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]

            user = User.objects.create_user(username, email, password)
            user.first_name = first_name
            user.last_name = last_name

            user.save()

            return HttpResponseRedirect('/')
    else:
        form = SignUpForm()

    data = {
        'form': form,
    }

    return render_to_response('maxfilm/signup.html', data,
                              context_instance=RequestContext(request))


@login_required
def dashboard(request):
    """Dashboard of the user"""

    if request.method == 'POST' and 'collections' not in request.GET and 'updateCollection' not in request.GET:
        aux = User.objects.get(username=request.user.username)
        if request.POST['password'] != '':
            aux.password = make_password(request.POST['password'])
        aux.email = request.POST['email']
        aux.first_name = request.POST['first_name']
        aux.last_name = request.POST['last_name']
        aux.save()

        return render(request, 'maxfilm/dashboard.html', {'profile': True,
                                                          'auxUser': aux,
                                                          'alert': True})

    if 'profile' in request.GET:
        aux = User.objects.get(username=request.user.username)

        return render(request, 'maxfilm/dashboard.html', {'profile': True,
                                                          'auxUser': aux})

    if 'movies' in request.GET:
        bookmarks = AccionPelicula.objects.filter(id_usuario=request.user).filter(favorita=True)
        pending = AccionPelicula.objects.filter(id_usuario=request.user).filter(pendiente=True)
        viewed = AccionPelicula.objects.filter(id_usuario=request.user).filter(vista=True)

        return render(request, 'maxfilm/dashboard.html', {'bookmarks': bookmarks,
                                                          'pending': pending,
                                                          'viewed': viewed,
                                                          'movies': True})

    if 'tv' in request.GET:
        bookmarks = AccionSerie.objects.filter(id_usuario=request.user).filter(favorita=True)
        pending = AccionSerie.objects.filter(id_usuario=request.user).filter(pendiente=True)
        viewed = AccionSerie.objects.filter(id_usuario=request.user).filter(vista=True)

        return render(request, 'maxfilm/dashboard.html', {'bookmarks': bookmarks,
                                                          'pending': pending,
                                                          'viewed': viewed,
                                                          'tv': True})

    if 'people' in request.GET:
        bookmarks = AccionPersona.objects.filter(id_usuario=request.user).filter(favorita=True)

        return render(request, 'maxfilm/dashboard.html', {'bookmarks': bookmarks,
                                                          'people': True})

    if 'deleteCollection' in request.GET:
        Coleccion.objects.get(id=request.GET['id']).delete()

        return redirect('/dashboard?collections')

    if 'updateCollection' in request.GET:
        aux = Coleccion.objects.get(id=request.GET['id'])

        if request.method == 'POST':
            aux.nombre = request.POST['nombre']
            aux.descripcion = request.POST['descripcion']
            aux.save()

            return HttpResponseRedirect('/dashboard/?collections')

        return render(request, 'maxfilm/dashboard.html', {'collection': aux,
                                                          'editCollection': True})

    if 'delete' in request.GET:
        ContenidoMultimedia.objects.filter(id=request.GET['id']).delete()

        return redirect('/dashboard?collections')

    if 'viewC' in request.GET:
        aux = Coleccion.objects.get(id=request.GET['id'])
        collection = ContenidoMultimedia.objects.filter(id_coleccion=aux)

        return render(request, 'maxfilm/dashboard.html', {'collection': collection,
                                                          'viewCollection': True,
                                                          'media': aux.media,
                                                          'nombre': aux.nombre})

    if 'collections' in request.GET:
        collectionsMovies = Coleccion.objects.filter(id_usuario=request.user).filter(media='Películas')
        collectionsTv = Coleccion.objects.filter(id_usuario=request.user).filter(media='Series')

        if request.method == 'POST':
            form = CollectionForm(request.POST)
            if form.is_valid():
                aux = Coleccion()
                aux.nombre = form.cleaned_data["nombre"]
                aux.descripcion = form.cleaned_data["descripcion"]
                aux.media = form.cleaned_data["media"]
                aux.id_usuario = request.user
                aux.save()

                return HttpResponseRedirect('/dashboard/?collections')
        else:
            form = CollectionForm()

        return render(request, 'maxfilm/dashboard.html', {'collections': True,
                                                          'form': form,
                                                          'collectionsTv': collectionsTv,
                                                          'collectionsMovies': collectionsMovies})

    con = Request('http://api.themoviedb.org/3/discover/movie?api_key=c1b10ae4b99ead975d0cbaf0d1045bf0&language=es',
                  headers=headers)
    numMovies = json.loads(urlopen(con).read())['total_results']

    con = Request('http://api.themoviedb.org/3/discover/tv?api_key=c1b10ae4b99ead975d0cbaf0d1045bf0&language=es',
                  headers=headers)
    numTv = json.loads(urlopen(con).read())['total_results']

    con = Request('http://api.themoviedb.org/3/person/popular?&api_key=c1b10ae4b99ead975d0cbaf0d1045bf0&language=es',
                  headers=headers)
    numPeople = json.loads(urlopen(con).read())['total_results']

    total = int(numMovies) + int(numTv) + int(numPeople)

    return render(request, 'maxfilm/dashboard.html', {'default': True,
                                                      'numMovies': numMovies,
                                                      'numTv': numTv,
                                                      'numPeople': numPeople,
                                                      'total': total})


def viewed(request):
    """Viewed"""

    if 'movie' in request.GET and 'delete' not in request.GET:
        con = Request('http://api.themoviedb.org/3/movie/' + request.GET['id'] +
                      '?api_key=c1b10ae4b99ead975d0cbaf0d1045bf0&language=es',
                      headers=headers)
        movie = json.loads(urlopen(con).read())

        try:
            aux = AccionPelicula.objects.filter(id_usuario=request.user.id).get(id_MovieAPI=request.GET['id'])
            aux.pendiente = False
            aux.vista = True
            aux.save()
        except AccionPelicula.DoesNotExist:
            aux = AccionPelicula()
            aux.id_MovieAPI = movie['id']
            aux.titulo = movie['title']
            aux.img_portada = movie['poster_path']
            aux.pendiente = False
            aux.vista = True
            aux.favorita = False
            aux.id_usuario = request.user
            aux.save()

        return redirect('/movie/' + request.GET['id'])

    if 'movie' in request.GET and 'delete' in request.GET:
        aux = AccionPelicula.objects.get(id=request.GET['id'])

        if aux.pendiente is False and aux.favorita is False:
            aux.delete()
        else:
            aux.vista = False
            aux.save()

        return redirect('/dashboard?movies')

    if 'tv' in request.GET and 'delete' not in request.GET:
        con = Request('http://api.themoviedb.org/3/tv/' + request.GET['id'] +
                      '?api_key=c1b10ae4b99ead975d0cbaf0d1045bf0&language=es',
                      headers=headers)
        tv = json.loads(urlopen(con).read())

        try:
            aux = AccionSerie.objects.filter(id_usuario=request.user.id).get(id_SerieAPI=request.GET['id'])

maxfilm/templates/maxfilm/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="ISO-8859-15">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>MaxFilm</title>
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="{% static 'css/slick-theme.css' %}" rel="stylesheet">  
  <link href="{% static 'css/slick.css' %}" rel="stylesheet">
  <link href="{% static 'css/datatables.min.css' %}" rel="stylesheet">
  <!--<link href='http://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>-->
  <style type="text/css">
  .form-group {
    width: 29%;
    margin-left: 80px;
  }

  #avatar {
    width: 126px;
    height: 128px;
    line-height: 128px;
    font-size: 48px;
    display: inline-block;
    background-color: #ccc;
    text-align: center;
    border-radius: 50%;
    color: white;
    text-transform: uppercase;
    margin-left: 60px;
  }

  .donut {
    width:100%;
    height:150px;
    min-width:150px;
  }

  .donut-label {
    position:absolute;
    left:45%;
    font-size:22pt;
    color:#ddd;
    width:100%;
    top:31%;
  }

  /* */
  .tt-dropdown-menu {
    text-align: left;
  }

  .title,
  .my-field-1 {
    font-family: Prociono;
  }

  .title {
    margin: 20px 0 0 0;
    font-size: 64px;
  }

  .example {
    padding: 30px 0;
  }

  .course-title {
    margin: 20px 0;
    font-size: 32px;
  }

  .demo {
    position: relative;
    *z-index: 1;
    margin: 50px 0;
  }

  .typeahead, .tt-query, .tt-hint {
    width: 396px !important;
    height: 30px !important;
    padding: 8px 12px !important;
    font-size: 24px !important;
    line-height: 30px !important;
    border: 2px solid #ccc !important;
    -webkit-border-radius: 8px;
    -moz-border-radius: 8px;
    border-radius: 8px !important;
    outline: none !important;
  }

  .typeahead {
    background-color: #fff;
  }

  .typeahead:focus {
    border: 2px solid #0097cf;
  }

  .tt-query {
    -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
    -moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
    box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
  }

  .tt-hint {
    color: #999
  }

  .tt-dropdown-menu {
    width: 422px;
    margin-top: 12px;
    padding: 8px 0;
    background-color: #fff;
    border: 1px solid #ccc;
    border: 1px solid rgba(0, 0, 0, 0.2);
    -webkit-border-radius: 8px;
    -moz-border-radius: 8px;
    border-radius: 8px;
    -webkit-box-shadow: 0 5px 10px rgba(0,0,0,.2);
    -moz-box-shadow: 0 5px 10px rgba(0,0,0,.2);
    box-shadow: 0 5px 10px rgba(0,0,0,.2);
  }

  .tt-suggestion {
    padding: 3px 20px;
    font-size: 18px;
    line-height: 24px;
  }

  .tt-suggestion.tt-is-under-cursor {
    color: #fff;
    background-color: #0097cf;

  }

  .tt-suggestion p {
    margin: 0;
  }

  .example-twitter-oss .tt-suggestion {
    padding: 8px 20px;
  }

  .example-twitter-oss .tt-suggestion + .tt-suggestion {
    border-top: 1px solid #ccc;
  }

  .example-twitter-oss .my-field-2 {
    float: right;
    font-style: italic;
  }

  .example-twitter-oss .my-field-1 {
    font-weight: bold;
  }

  .example-twitter-oss .my-field-3 {
    font-size: 14px;
  }
  /* */
  </style>
</head>
<body>
  <nav class="navbar z-depth-2 red">
    <div class="container ">
      <div class="navbar-header">
        <a class="navbar-brand waves-effect waves-light" href="{%url 'maxfilm:index'%}">MaxFilm</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="{%url 'maxfilm:index'%}" class="waves-effect waves-light">Inicio <span class="sr-only">(current)</span></a></li>
          <li><a href="{%url 'maxfilm:Movies'%}" class="waves-effect waves-light">Películas <span class="sr-only">(current)</span></a></li>
          <li><a href="{%url 'maxfilm:Tv'%}" class="waves-effect waves-light">Series <span class="sr-only">(current)</span></a></li>
          <li><a href="{%url 'maxfilm:People'%}" class="waves-effect waves-light">Personas <span class="sr-only">(current)</span></a></li>
          {% if user.is_authenticated %}
          <li><a href="{%url 'maxfilm:dashboard'%}" class="waves-effect waves-light">Perfil: {{user.username}} <span class="sr-only">(current)</span></a></li>
          {% endif %}
        </ul>
        <form class="navbar-form navbar-right waves-effect waves-light" role="search" action="/search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Buscar" name="text" required>
          </div>
        </form>
      </div>
    </div>
  </nav>
  {% block content %}
  {% endblock %}
  <div class="container">
    <hr>
  </div>
  <footer class="page-footer red darken-1" if="footer">
    <div class="container">
      <div class="row">
        <div class="col-md-3 col-md-offset-1">
          <p class="white-text center-on-small-only">COMENZAR</p>
          <a href="{%url 'maxfilm:signup'%}" class="btn btn-danger waves-effect waves-light">Regístrate!</a>
        </div>
        <hr class="hidden-lg hidden-md">
        <div class="col-md-2">
          <p class="white-text center-on-small-only">ENLACES</p>
          <ul>
            <li><a href="{%url 'maxfilm:index'%}" class="waves-effect waves-light">Inicio </a></li>
            <li><a href="{%url 'maxfilm:Movies'%}" class="waves-effect waves-light">Películas </a></li>
            <li><a href="{%url 'maxfilm:Tv'%}" class="waves-effect waves-light">Series </a></li>
            <li><a href="{%url 'maxfilm:People'%}" class="waves-effect waves-light">Personas </a></li>
          </ul>
        </div>
        <hr class="hidden-lg hidden-md">
        <div class="col-md-3 text-center">
          <p class="white-text text-center">REDES SOCIALES</p>
          <a target="_blank" href="#" class="btn-floating btn-large fb-bg waves-effect waves-light"><i class="fa fa-facebook"> </i></a>
          <a target="_blank" href="#" class="btn-floating btn-large tw-bg waves-effect waves-light"><i class="fa fa-twitter"> </i></a>
          <a target="_blank" href="#" class="btn-floating btn-large gplus-bg waves-effect waves-light"><i class="fa fa-google-plus"> </i></a>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
        <div class="col-md-10 col-md-offset-1"> 2016 <a href="{%url 'maxfilm:index'%}">MaxFilm </a>
        </div>
      </div>
    </div>
  </footer>
  <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/mdb.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/slick.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/datatables.min.js' %}"></script>
  <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.9.3/typeahead.min.js"></script>
  <script type="text/javascript">
  $(document).ready(function () {
    {% if default %}
    $.getScript('//cdnjs.cloudflare.com/ajax/libs/flot/0.8.2/jquery.flot.min.js',function(){
      $.getScript('//cdnjs.cloudflare.com/ajax/libs/flot/0.8.2/jquery.flot.pie.min.js',function(){
        $.getScript('//cdnjs.cloudflare.com/ajax/libs/flot/0.8.2/jquery.flot.resize.min.js',function(){

          var movies = ({{numMovies}} * 100) / {{total}};
          var restMovies = 100 - movies;

          var tv = ({{numTv}} * 100) / {{total}};
          var restTv = 100 - tv;

          var people = ({{numPeople}} * 100) / {{total}};
          var restPeople = 100 - people;

          $.plot("#chart1",[{data: movies,color:'#F44336'},{data: restMovies,color:'#ddd'}],{series:{pie:{show: true,innerRadius: 0.6}}});
          $.plot("#chart2",[{data: tv,color:'#33B5E5'},{data: restTv,color:'#ddd'}],{series:{pie:{show: true,innerRadius: 0.6}}});
          $.plot("#chart3",[{data: people,color:'#00C853'},{data: restPeople,color:'#ddd'}],{series:{pie:{show: true,innerRadius: 0.6}}});
        });
      });
    });
{% endif %}

$('#movies').typeahead({
  displayKey: 'value',
  header: '<b>Películas sugeridas...</b>',
  limit: 10,
  minLength: 1,
  remote: {
    url : 'http://api.themoviedb.org/3/search/movie?query=%QUERY&api_key=c1b10ae4b99ead975d0cbaf0d1045bf0&language=es',
    filter: function (parsedResponse) {               
      retval = [];
      for (var i = 0;  i < parsedResponse.results.length;  i++) {
        retval.push({
          value: parsedResponse.results[i].title,
          tokens: [parsedResponse.results[i].title]
        });
      }
      return retval;
    },
    dataType: 'jsonp'
  }
});

$('.autoplay').slick({
  infinite: true,
  speed: 500,
  slidesToShow: 5,
  slidesToScroll: 1,
  autoplay: true,
  autoplaySpeed: 2000
});

$('#tableCrew, #tableCast').DataTable( {
  "order": [[ 0, "desc" ]]
} );

{% if action %}
$({{action}}).toggleClass('active');
$('#status').children().each(function() {
  if ($(this).attr('id') == {{action}}) {
    $(this).toggleClass('active');
  };
});
{% endif %}

{% if genre %}
$('#genres').children().each(function() {
  if ($(this).attr('id') == "genre_" + {{genre}}) {
    $(this).toggleClass('active');
  };
});
{% endif %}

{% if page %}
$('#pagination').children().each(function() {
  if ($(this).attr('id') == {{page}}) {
    $(this).toggleClass('active');
  };
});
{% endif %}
});
</script>
</body>
</html>

maxfilm/templates/maxfilm/people.html
{% extends 'maxfilm/base.html' %}
{% load staticfiles %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="page-header">Personas</h1>
        </div>
    </div>
    <div class="row page-content">
        <div class="col-md-3">
            <div class="collection z-depth-2" id="status">
                <a class="collection-item blue text-center"><h4 class="white-text">Mostrar</h4></a>
                <a id="popular" class="collection-item" href="?query=popular">Populares</a>
            </div>
        </div>
        <div class="col-md-9">
            {% for person in people %}
            <div class="col-md-3">
                <div class="card hoverable text-center" style="height:540px">
                    <div class="card-image">
                        <img height="278" src="http://image.tmdb.org/t/p/w185/{{person.profile_path}}" onerror="this.src='{% static 'img/noprofile.jpg' %}';"/>
                    </div>
                    <div class="card-content" style="height:130px">
                        <p><b>{{person.name|truncatechars:40}}</b></p>
                    </div>
                    <div class="card-action text-center">
                        <a href="{%url 'maxfilm:viewPerson' id=person.id%}" class="btn btn-default waves-effect waves-light center-block">Mostrar</a>
                    </div>
                </div>
            </div>
            {% endfor %}
            <div class="row">
                <div class="col-md-10 col-md-offset-3">
                    <ul class="pagination pag-circle" id="pagination">
                        <li><a href="#!"><i class="material-icons">chevron_left</i></a></li>
                        <li id="1"><a href="?page=1">1</a></li>
                        <li id="2"><a href="?page=2">2</a></li>
                        <li id="3"><a href="?page=3">3</a></li>
                        <li id="4"><a href="?page=4">4</a></li>
                        <li id="5"><a href="?page=5">5</a></li>
                        <li id="6"><a href="?page=6">6</a></li>
                        <li id="7"><a href="?page=7">7</a></li>
                        <li id="8"><a href="?page=8">8</a></li>
                        <li id="9"><a href="?page=9">9</a></li>
                        <li id="10"><a href="?page=10">10</a></li>
                        <li><a href="#!"><i class="material-icons">chevron_right</i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}